### ISSUE TITLE
Some problems about the other repo

### ISSUE THREAD

**Issue by NinetailsBear9** [PatWie/tensorflow_inference#3]
I'm so sorry for asking problem here, because there isn't issues module of that  repo and i can't find your email address(i can't send an email to the address which is on your profile page with my stupid email system )
It's about the learning-blind-motion-deblurring repo
I follow the step of the repo
the result of step2 is the version of average frames and camera shake? or just camera shake?
the result of step3 is much more blurry than the result of step2, but in the data_sampler.py, the L(parameter name: avg_frames) is set as 1(means no average will be done)
I want to know where did you do the average?
Apologize again for my problem.
....................
after reading the data_provider.py, so the PSF just convolve on the data when show the data? but not on the data which you used when you training?

**Comment by PatWie** [comment]
Feel free to drop me an email mail@patwie.com.
Closed as this is not related to this repo.
