### ISSUE TITLE
issue about make 

### ISSUE THREAD

**Issue by minmingzhao** [PatWie/tensorflow_inference#4]
Apologize if it is a silly question.

I am running c++ inference. After `cmake .` and then `make`, I have following error. 
```
xxxx-MBP:cc userP$ make
[ 50%] Building CXX object CMakeFiles/inference_cc.dir/inference_cc.cc.o
[ 50%] Linking CXX executable inference_cc
ld: unknown option: --allow-multiple-definition
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/inference_cc.dir/build.make:97: inference_cc] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/inference_cc.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Could you help? Thanks!

**Comment by PatWie** [comment]
I never got that issue. Looking at
https://linux.die.net/man/1/ld

you should try the `-z` flag

**Comment by minmingzhao** [comment]
Thanks for the reply. Yes, I am using OSX. I will keep digging then.

**Comment by wsjeon** [comment]
I also got the same error in OSX. Did you solve this issue? @minmingzhao
